import 'package:flutter/material.dart';

Color primaryColor = Color(0xFF8B84FB);
Color inactivePrimaryColor = Color(0xFFE9E8FC);
Color inputBorderColor = Color(0xFFD6D4D4);
Color secondTextColor = Color(0xFF9A9A9A);

Color selectZoneColor = Color(0xFFEDEEEE);

TextStyle secondaryTextStyle = TextStyle(color: secondTextColor, fontSize: 12);

String dataTest =
    "{\"avatar\":null,\"firstName\":\"Marie\",\"lastName\":\"Dubois\",\"age\":\"27\",\"city\":\"Paris\",\"email\":\"marie.dubois@email.com\",\"phone\":\"0606060606\",\"aboutMe\":\"Je m'appelle Marie, dans la vie j'aime la culture Japonaise, la musique (composition musicale), les jeux vidéo, la lecture, le dessin et surtout le cinéma.\",\"experiences\":[{\"job\":\"Responsable rayon\",\"company\":\"Entreprise A\",\"from\":\"2020-01-22 00:00:00.000\",\"to\":\"null\",\"description\":\"Vente conseil merchandising et facing.\\nCo-gestion des rayons TV, PEM et Gaming.\\nSAV Événementiel, formation des collaborateurs\"},{\"job\":\"Conseillère technico-commercial en agence\",\"company\":\"Entreprise B\",\"from\":\"2019-06-22 00:00:00.000\",\"to\":\"2019-12-22 00:00:00.000\",\"description\":\"Vente conseil merchandising et facing.\\nÉvénementiel.\\nCo-gestion du pôle SAV\\nFormation des collaborateurs\"},{\"job\":\"Vendeuse conseil\",\"company\":\"Entreprise C\",\"from\":\"2019-01-22 00:00:00.000\",\"to\":\"2019-05-22 00:00:00.000\",\"description\":\"Vente conseil merchandising et facing\\nSAV\\nÉvénementiel\"},{\"job\":\"Vendeuse conseil\",\"company\":\"Entreprise D\",\"from\":\"2018-06-22 00:00:00.000\",\"to\":\"2018-12-22 00:00:00.000\",\"description\":\"Vente conseil merchandising et facing\"}],\"degrees\":[{\"degree\":\"BTS Management des unités commerciales\",\"school\":\"École supérieure de commerce\",\"from\":\"2016-09-22 00:00:00.000\",\"to\":\"2018-07-22 00:00:00.000\",\"description\":\"Bac +2 ou équivalent - Direction des entreprises, CFA centre de formation des apprentis\"},{\"degree\":\"Bac commerce\",\"school\":\"Lycée professionnel A\",\"from\":\"2012-09-22 00:00:00.000\",\"to\":\"2016-07-22 00:00:00.000\",\"description\":\"Bac ou équivalent - Direction des entreprises, CFA centre de formation des apprentis\"},{\"degree\":\"BEPA Vente\",\"school\":\"Collège privé A\",\"from\":\"2008-09-22 00:00:00.000\",\"to\":\"2012-07-22 00:00:00.000\",\"description\":\"CAP BEP ou équivalent - Direction des entreprises, CFA centre de formation des apprentis\"}],\"skills\":[{\"skill\":\"Vente\",\"level\":\"90\"},{\"skill\":\"SAV\",\"level\":\"70\"},{\"skill\":\"Merchandising\",\"level\":\"70\"},{\"skill\":\"Gestion de projet\",\"level\":\"60\"},{\"skill\":\"Bureautique\",\"level\":\"70\"},{\"skill\":\"Événementiel\",\"level\":\"91\"},{\"skill\":\"Gestion d'équipe\",\"level\":\"50\"},{\"skill\":\"Management\",\"level\":\"50\"}],\"languages\":[{\"language\":\"fr\",\"level\":\"LanguageEnum.expert\"},{\"language\":\"en\",\"level\":\"LanguageEnum.high\"}],\"model\":\"01\"}";
